__default__:
    time: 00:30:00
    job-name:  RNAseq
    account: project_2002561
    ntasks: 1
    cpus-per-task: 1
    mem-per-cpu: 4000
    partition: small
    working-directory: /scratch/project_2002561/MastitisChallenge/logs/
    nvme: 0

# Step1 - Preparations
################################################################################

star_create_index:
    job-name: star_index
    time: 08:00:00
    mem-per-cpu: 4000
    cpus-per-task: 20

rsem_create_index:
    job-name: rsem_index
    time: 0-10:00:00
    cpus-per-task: 20

# Step2 - Preprocessing
################################################################################
 
fastp_trim_reads:
    job-name: fastp
    time: 01:00:00
    cpus-per-task: 10
    
# Step3 - QC
################################################################################
fastqc_quality_control_raw_data:
    job-name: fastqc_raw_data
    time: 01:00:00
    cpus-per-task: 20

multiqc_quality_control_raw_data:
    job-name: multiqc_raw_data
    time: 00:30:00
    cpus-per-task: 1

fastqc_quality_control_concatenated_data:
    job-name: fastqc_concatenated_data
    time: 01:00:00
    cpus-per-task: 20

multiqc_quality_control_concatenated_data:
    job-name: multiqc_concatenated_data
    time: 00:30:00
    cpus-per-task: 1

fastqc_quality_control_trimmed_data:
    job-name: fastqc_trimmed_data
    time: 01:00:00
    cpus-per-task: 20

multiqc_quality_control_trimmed_data:
    job-name: multiqc_trimmed_data
    time: 00:30:00
    cpus-per-task: 1

# Step4 - Alignment
################################################################################
    
star_map_reads:
    job-name: star_mapReads
    time: 04:00:00
    cpus-per-task: 20
    
# Step5 - TranscriptomeAssembly
################################################################################

transcriptome_assembly_stringtie:    
    job-name: stringtie
    time: 04:00:00
    cpus-per-task: 20
    
merge_samples:
    job-name: mergSTRGeSamples
    time: 04:00:00
    cpus-per-task: 20
    
# Step6 - Quantification
################################################################################

rsem_calculate_expressions:
    job-name: rsem_quant
    time: 0-06:00:00
    cpus-per-task: 20

featureCounts_quantify:
    job-name: fc_quantify
    time: 06:00:00
    cpus-per-task: 20

featureCounts_quantify_merged:
    job-name: fc_quantify_merged
    time: 06:00:00
    cpus-per-task: 20